### ISSUE TITLE
spawners.json missing properties

### ISSUE THREAD

**Issue by Oipo** [LandOfTheRair/Content#4]
Some spawners in the output are, f.e., missing the "doInitialSpawnImmediately" property. It would be a great help if this property is present for all spawners.

The list of properties I expect per spawner in the spawners.json:
```
tag
respawnRate
initialSpawn
maxSpawn
maxCreatures
spawnRadius
randomWalkRadius
leashRadius
eliteTickCap
shouldSerialize
alwaysSpawn
requireDeadToRespawn
canSlowDown
doInitialSpawnImmediately
npcIds (at least an empty array)
```

**Comment by seiyria** [comment]
[Here](https://github.com/LandOfTheRair/landoftherair/blob/master/src/server/base/Spawner.ts#L18-L77) is what all properties default to.

If there are no `npcIds`, that means the property should be inferred from the map (this happens with Lair spawners and Resource spawners).
